[package]
name = "rust-rocket-api"
version = "0.1.0"
authors = ["JD Gonzales <jd_gonzales@icloud.com>"]

[dependencies]
rocket = "0.3.0"
rocket_codegen = "0.3.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

[dependencies.rocket_contrib]
default-features = false
features = ["json"]
